server {
    listen 80 default_server;
    server_name _;

    location /prod/actuator/prometheus {
        allow 10.0.1.49;
        deny all;
        proxy_pass http://127.0.0.1:8080/actuator/prometheus;
    }

    location /dev/actuator/prometheus {
        allow 10.0.1.49;
        deny all;
        proxy_pass http://127.0.0.1:8081/actuator/prometheus;
    }
}
