name: Deploy PROD

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-prod
  cancel-in-progress: false

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  deploy:
    needs: ci
    uses: ./.github/workflows/deploy-common.yml
    with:
      profile: prod
      service_name: fmi-prod
      image_tag: prod
    secrets: inherit